
class RedisConstant:

    REDIS_TIME_EXPIRED = 360
    REDIS_USER_NAME = 'USER-NAME:'
    REDIS_TOTAL_AMOUNT = 'TOTAL_AMOUNT'
    REDIS_CURRENT_POSITION = 'CURRENT_POSITION'
    REDIS_CURRENT_WORD = 'CURRENT_WORD'
    REDIS_LIST = 'LIST'
    REDIS_LEARNING_SET = 'LEARNING_SET'