"""Level add autoincrement

Revision ID: 8ae6fb16eddd
Revises: 22e2d022fe41
Create Date: 2024-06-10 20:14:25.700395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae6fb16eddd'
down_revision: Union[str, None] = '22e2d022fe41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
