"""Level param is unique

Revision ID: 5b6e2d361020
Revises: 7c4f9f467337
Create Date: 2024-06-11 11:04:40.814318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6e2d361020'
down_revision: Union[str, None] = '7c4f9f467337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lang_level', ['lang_level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lang_level', type_='unique')
    # ### end Alembic commands ###
