"""Add unique link in word table - between german_word and user_id

Revision ID: fbd615bcd026
Revises: c584912967c8
Create Date: 2024-07-27 21:52:03.741865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd615bcd026'
down_revision: Union[str, None] = 'c584912967c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'training_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_german_word_user_id', 'word', ['german_word', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_german_word_user_id', 'word', type_='unique')
    op.alter_column('user', 'training_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
