"""Add UniqueConstraint to Table Standard_word_user 

Revision ID: ffe377c71a69
Revises: 9b8527a16a9a
Create Date: 2024-07-28 17:32:54.316035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe377c71a69'
down_revision: Union[str, None] = '9b8527a16a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_word_id_user_id', 'standard_word_user', ['word_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_word_id_user_id', 'standard_word_user', type_='unique')
    # ### end Alembic commands ###
