"""Add table progress for detecting user learning progress

Revision ID: 3fcf2819beca
Revises: b6d143e83641
Create Date: 2024-06-25 13:49:39.127202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcf2819beca'
down_revision: Union[str, None] = 'b6d143e83641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
