"""Change Level: from enum to str

Revision ID: d80c1259ceb0
Revises: c7587ecd8aa1
Create Date: 2024-08-21 10:41:09.846147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd80c1259ceb0'
down_revision: Union[str, None] = 'c7587ecd8aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lang_level', 'lang_level',
               existing_type=postgresql.ENUM('a1', 'a2', 'b1', 'b2', 'c1', 'c2', name='levelenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lang_level', 'lang_level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('a1', 'a2', 'b1', 'b2', 'c1', 'c2', name='levelenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
