"""Update user - add telegram_id

Revision ID: de10f55ef67d
Revises: 5b6e2d361020
Create Date: 2024-06-24 17:27:42.459138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de10f55ef67d'
down_revision: Union[str, None] = '5b6e2d361020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_user_id')
    # ### end Alembic commands ###
