"""Level add autoincrement

Revision ID: 7c4f9f467337
Revises: 8ae6fb16eddd
Create Date: 2024-06-11 10:42:47.872583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f9f467337'
down_revision: Union[str, None] = '8ae6fb16eddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'word_type', ['word_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_type', type_='unique')
    # ### end Alembic commands ###
