"""Change WordType: from enum to str

Revision ID: c7587ecd8aa1
Revises: 633a876b8a07
Create Date: 2024-08-20 21:46:58.728574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7587ecd8aa1'
down_revision: Union[str, None] = '633a876b8a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_type', 'word_type',
               existing_type=postgresql.ENUM('standard', 'custom', name='wordtypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_type', 'word_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('standard', 'custom', name='wordtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
