"""Update Word table (make english word optional)

Revision ID: 07e9b0e9bb9e
Revises: 387204e2974c
Create Date: 2024-07-03 17:21:22.584665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e9b0e9bb9e'
down_revision: Union[str, None] = '387204e2974c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
