"""Update table User training_length field - default = 10

Revision ID: c584912967c8
Revises: 28ee946e5e3b
Create Date: 2024-07-23 12:24:12.152743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c584912967c8'
down_revision: Union[str, None] = '28ee946e5e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('training_length', sa.Integer(), nullable=True))
    op.execute("UPDATE \"user\" SET training_length = 10")
    op.alter_column('user', 'training_length', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'training_length')
    # ### end Alembic commands ###
