"""Delete table progress  

Revision ID: c6ec017edca1
Revises: 119c7ab00123
Create Date: 2024-06-25 14:56:58.715928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ec017edca1'
down_revision: Union[str, None] = '119c7ab00123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.add_column('word', sa.Column('amount_already_know', sa.Integer(), nullable=False))
    op.add_column('word', sa.Column('amount_back_to_learning', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'amount_back_to_learning')
    op.drop_column('word', 'amount_already_know')
    op.create_table('progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_already_know', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_back_to_learning', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='progress_user_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name='progress_word_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='progress_pkey')
    )
    # ### end Alembic commands ###
